//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SdblClient.SdblSvcRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dbsoft.de/SoapSvr/SdblService/", ConfigurationName="SdblSvcRef.SdblServiceSoap")]
    public interface SdblServiceSoap {
        
        // CODEGEN: Generating message contract since element name HANDELSBEZEICHNUNG from namespace http://dbsoft.de/SoapSvr/SdblService/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dbsoft.de/SoapSvr/SdblService/UploadSDB", ReplyAction="*")]
        SdblClient.SdblSvcRef.UploadSDBResponse UploadSDB(SdblClient.SdblSvcRef.UploadSDBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dbsoft.de/SoapSvr/SdblService/UploadSDB", ReplyAction="*")]
        System.Threading.Tasks.Task<SdblClient.SdblSvcRef.UploadSDBResponse> UploadSDBAsync(SdblClient.SdblSvcRef.UploadSDBRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadSDBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadSDB", Namespace="http://dbsoft.de/SoapSvr/SdblService/", Order=0)]
        public SdblClient.SdblSvcRef.UploadSDBRequestBody Body;
        
        public UploadSDBRequest() {
        }
        
        public UploadSDBRequest(SdblClient.SdblSvcRef.UploadSDBRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dbsoft.de/SoapSvr/SdblService/")]
    public partial class UploadSDBRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HANDELSBEZEICHNUNG;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SPRACHE;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string VKORG;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DOKU_TYP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string LOESCH_KNZ;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string INTERNET_KNZ;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MINERAL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string BESCHICHTUNG;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string KOERNUNG;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string SDB_BASE64;
        
        public UploadSDBRequestBody() {
        }
        
        public UploadSDBRequestBody(string HANDELSBEZEICHNUNG, string SPRACHE, string VKORG, string DOKU_TYP, string LOESCH_KNZ, string INTERNET_KNZ, string MINERAL, string BESCHICHTUNG, string KOERNUNG, string SDB_BASE64) {
            this.HANDELSBEZEICHNUNG = HANDELSBEZEICHNUNG;
            this.SPRACHE = SPRACHE;
            this.VKORG = VKORG;
            this.DOKU_TYP = DOKU_TYP;
            this.LOESCH_KNZ = LOESCH_KNZ;
            this.INTERNET_KNZ = INTERNET_KNZ;
            this.MINERAL = MINERAL;
            this.BESCHICHTUNG = BESCHICHTUNG;
            this.KOERNUNG = KOERNUNG;
            this.SDB_BASE64 = SDB_BASE64;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadSDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadSDBResponse", Namespace="http://dbsoft.de/SoapSvr/SdblService/", Order=0)]
        public SdblClient.SdblSvcRef.UploadSDBResponseBody Body;
        
        public UploadSDBResponse() {
        }
        
        public UploadSDBResponse(SdblClient.SdblSvcRef.UploadSDBResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dbsoft.de/SoapSvr/SdblService/")]
    public partial class UploadSDBResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadSDBResult;
        
        public UploadSDBResponseBody() {
        }
        
        public UploadSDBResponseBody(string UploadSDBResult) {
            this.UploadSDBResult = UploadSDBResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SdblServiceSoapChannel : SdblClient.SdblSvcRef.SdblServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SdblServiceSoapClient : System.ServiceModel.ClientBase<SdblClient.SdblSvcRef.SdblServiceSoap>, SdblClient.SdblSvcRef.SdblServiceSoap {
        
        public SdblServiceSoapClient() {
        }
        
        public SdblServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SdblServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SdblServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SdblServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SdblClient.SdblSvcRef.UploadSDBResponse SdblClient.SdblSvcRef.SdblServiceSoap.UploadSDB(SdblClient.SdblSvcRef.UploadSDBRequest request) {
            return base.Channel.UploadSDB(request);
        }
        
        public string UploadSDB(string HANDELSBEZEICHNUNG, string SPRACHE, string VKORG, string DOKU_TYP, string LOESCH_KNZ, string INTERNET_KNZ, string MINERAL, string BESCHICHTUNG, string KOERNUNG, string SDB_BASE64) {
            SdblClient.SdblSvcRef.UploadSDBRequest inValue = new SdblClient.SdblSvcRef.UploadSDBRequest();
            inValue.Body = new SdblClient.SdblSvcRef.UploadSDBRequestBody();
            inValue.Body.HANDELSBEZEICHNUNG = HANDELSBEZEICHNUNG;
            inValue.Body.SPRACHE = SPRACHE;
            inValue.Body.VKORG = VKORG;
            inValue.Body.DOKU_TYP = DOKU_TYP;
            inValue.Body.LOESCH_KNZ = LOESCH_KNZ;
            inValue.Body.INTERNET_KNZ = INTERNET_KNZ;
            inValue.Body.MINERAL = MINERAL;
            inValue.Body.BESCHICHTUNG = BESCHICHTUNG;
            inValue.Body.KOERNUNG = KOERNUNG;
            inValue.Body.SDB_BASE64 = SDB_BASE64;
            SdblClient.SdblSvcRef.UploadSDBResponse retVal = ((SdblClient.SdblSvcRef.SdblServiceSoap)(this)).UploadSDB(inValue);
            return retVal.Body.UploadSDBResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SdblClient.SdblSvcRef.UploadSDBResponse> SdblClient.SdblSvcRef.SdblServiceSoap.UploadSDBAsync(SdblClient.SdblSvcRef.UploadSDBRequest request) {
            return base.Channel.UploadSDBAsync(request);
        }
        
        public System.Threading.Tasks.Task<SdblClient.SdblSvcRef.UploadSDBResponse> UploadSDBAsync(string HANDELSBEZEICHNUNG, string SPRACHE, string VKORG, string DOKU_TYP, string LOESCH_KNZ, string INTERNET_KNZ, string MINERAL, string BESCHICHTUNG, string KOERNUNG, string SDB_BASE64) {
            SdblClient.SdblSvcRef.UploadSDBRequest inValue = new SdblClient.SdblSvcRef.UploadSDBRequest();
            inValue.Body = new SdblClient.SdblSvcRef.UploadSDBRequestBody();
            inValue.Body.HANDELSBEZEICHNUNG = HANDELSBEZEICHNUNG;
            inValue.Body.SPRACHE = SPRACHE;
            inValue.Body.VKORG = VKORG;
            inValue.Body.DOKU_TYP = DOKU_TYP;
            inValue.Body.LOESCH_KNZ = LOESCH_KNZ;
            inValue.Body.INTERNET_KNZ = INTERNET_KNZ;
            inValue.Body.MINERAL = MINERAL;
            inValue.Body.BESCHICHTUNG = BESCHICHTUNG;
            inValue.Body.KOERNUNG = KOERNUNG;
            inValue.Body.SDB_BASE64 = SDB_BASE64;
            return ((SdblClient.SdblSvcRef.SdblServiceSoap)(this)).UploadSDBAsync(inValue);
        }
    }
}
